- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          export BASE='/opt/stack'
          export FLOCXCLIENT_DIR="$BASE/python-flocxclient"
          sudo chmod -R a+rw /opt/stack/
          cd $FLOCXCLIENT_DIR
          set +e
          echo "Running flocxclient functional test suite"
          # Only admin credentials needed for flocx api
          source $BASE/devstack/openrc admin admin
          FUNC_TEST_DIR=$FLOCXCLIENT_DIR/flocxclient/tests/functional
          CONFIG_FILE=$FLOCXCLIENT_DIR/test.conf
          echo 'Generating configuration file for functional tests'
          if [[ -n "$FLOCX_URL" ]]; then
          cat <<END >$CONFIG_FILE
          [functional]
          api_version = 1
          auth_strategy=noauth
          flocx_url=$FLOCX_URL
          END
          else
          cat <<END >$CONFIG_FILE
          [functional]
          api_version = 1
          os_auth_url=$OS_AUTH_URL
          os_identity_api_version=$OS_IDENTITY_API_VERSION
          os_username=$OS_USERNAME
          os_password=$OS_PASSWORD
          os_project_name=$OS_PROJECT_NAME
          os_user_domain_id=$OS_USER_DOMAIN_ID
          os_project_domain_id=$OS_PROJECT_DOMAIN_ID
          os_service_type=market
          os_endpoint_type=public
          END
          fi
          echo 'Configuration file is in '$CONFIG_FILE''
          export FLOCXCLIENT_TEST_CONFIG=$CONFIG_FILE
          cd $FLOCXCLIENT_DIR
          echo 'Running Functional Tests under Python3'
          tox -e functionalpy3
        executable: /bin/bash
        chdir: '/opt/stack/python-flocxcclient'