- job:
    name: flocxclient-functional
    parent: devstack-minimal
    run: playbooks/functional/run.yaml
    timeout: 7200
    required-projects:
      - openstack/devstack-gate
      - openstack/flocxmarket
      - openstack/python-flocxclient

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - flocxclient-functional
    gate:
      jobs:
        - flocxclient-functional